#!/usr/bin/env python3
"""Compile game TOML manifests into immutable runtime chip tables (no ROM bytes)."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from recomp.roms import REGIONS, region_spec


def video_settings(config: dict, path: Path) -> tuple[tuple, str]:
    """Validated [video] values and their VideoConfig initializer (shared by both outputs)."""
    video = config.get("video", {})
    rotation = video.get("rotation", 0)
    lag = video.get("sprite_lag", 1)
    y = video.get("visible_y", 24)
    height = video.get("visible_height", 232)
    extend = video.get("extend", True)
    extended_alt_maps = video.get("extended_alt_maps", False)
    full_resolution_alt_maps = video.get("full_resolution_alt_maps", False)
    if (rotation not in (0, 90, 180, 270) or lag not in (0, 1, 2) or
            not 0 <= y < y + height <= 256 or not isinstance(extend, bool) or
            not isinstance(extended_alt_maps, bool) or not isinstance(full_resolution_alt_maps, bool)):
        raise ValueError(f"Unsupported video configuration: {path}")
    if full_resolution_alt_maps and not extended_alt_maps:
        raise ValueError(f"video.full_resolution_alt_maps requires video.extended_alt_maps: {path}")
    settings = (f"{{ {rotation}, {lag}, {y}, {height}, {str(extend).lower()}, "
                f"{str(extended_alt_maps).lower()}, {str(full_resolution_alt_maps).lower()} }}")
    return (rotation, lag, y, height, extend, extended_alt_maps, full_resolution_alt_maps), settings


def write_if_changed(path: Path, text: str) -> None:
    if not path.is_file() or path.read_text(encoding="utf-8") != text:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def generate_game_config(config_path: Path, game: str, output: Path) -> None:
    config = tomllib.loads(config_path.read_text())
    if config["game"]["id"] != game:
        raise ValueError(f"Config {config_path} is not game {game}")
    _, settings = video_settings(config, config_path)
    text = f"""// Generated by tools/compile_roms.py from games/{game}/config.toml. No ROM data.
#pragma once
#include <string_view>
#include "f3rt/rom.hpp"

namespace f3rt::game_config {{
inline constexpr std::string_view id = {json.dumps(game)};
inline constexpr VideoConfig video{settings};
inline constexpr unsigned visible_end = video.visible_y + video.visible_height;
static_assert(video.visible_y + video.visible_height <= 256 && video.visible_height > 0,
              "visible window must fit the 256-line frame");
static_assert(!video.full_resolution_alt_maps || video.extended_alt_maps,
              "full_resolution_alt_maps requires extended_alt_maps");
// Startup consistency check: a loaded set must carry the geometry this build was compiled for.
constexpr bool matches(const VideoConfig &v) {{
    return v.rotation == video.rotation && v.sprite_lag == video.sprite_lag &&
           v.visible_y == video.visible_y && v.visible_height == video.visible_height &&
           v.extend == video.extend && v.extended_alt_maps == video.extended_alt_maps &&
           v.full_resolution_alt_maps == video.full_resolution_alt_maps;
}}
}} // namespace f3rt::game_config
"""
    write_if_changed(output, text)


def generate(configs: list[Path], output: Path) -> None:
    lines = [
        "// Generated by tools/compile_roms.py. No ROM data.\n#pragma once\n",
        '#include "f3rt/rom.hpp"\n#include <array>\n#include <span>\n#include <string_view>\n',
        "namespace f3rt::rom_manifest {\n",
        "struct Chip { const char *file; size_t size; uint32_t crc; const char *sha1; size_t short_size; "
        "uint32_t short_crc; const char *short_sha1; size_t offset, stride, group, source_offset, length; };\n",
        "struct Region { size_t size, mapped_size; uint8_t fill; std::span<const Chip> chips; };\n",
        "struct Game { std::string_view id; VideoConfig video; std::array<Region, 8> regions; };\n",
    ]
    games = []
    ids = set()
    for index, path in enumerate(configs):
        config = tomllib.loads(path.read_text())
        identity = config["game"]["id"]
        if identity in ids:
            raise ValueError(f"Duplicate game id: {identity}")
        ids.add(identity)
        regions = []
        for name in REGIONS:
            size, fill, chips = region_spec(config, name)
            table = f"chips_{index}_{name}"
            lines.append(f"inline constexpr std::array<Chip, {len(chips)}> {table} = {{{{\n")
            for chip in chips:
                values = [json.dumps(chip["file"]), str(chip["size"]), f"0x{chip['crc']}u",
                          json.dumps(chip["sha1"]), str(chip.get("short_size", 0)),
                          f"0x{chip.get('short_crc', '0')}u", json.dumps(chip.get("short_sha1", "")),
                          *(str(chip[key]) for key in
                            ("offset", "stride", "group", "source_offset", "length"))]
                lines.append("    { " + ", ".join(values) + " },\n")
            lines.append("}};\n")
            mapped_size = config.get(name, {}).get("mirror_size", size)
            if mapped_size < size or (size and mapped_size % size) or (not size and mapped_size):
                raise ValueError(f"Invalid mirrored region size: {path}: {name}")
            regions.append(f"{{ {size}, {mapped_size}, {fill}, {table} }}")
        settings = video_settings(config, path)[1]
        games.append(f"    {{ {json.dumps(identity)}, {settings}, {{{{ " + ", ".join(regions) + " }} },\n")
    lines.append(f"inline constexpr std::array<Game, {len(games)}> games = {{{{\n")
    lines.extend(games)
    lines.append("}};\n} // namespace f3rt::rom_manifest\n")
    write_if_changed(output, "".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--configs", nargs="+", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--game", help="F3_GAME id; with --game-output writes game_video_config.hpp")
    parser.add_argument("--game-output", type=Path)
    args = parser.parse_args()
    if bool(args.game) != bool(args.game_output):
        parser.error("--game and --game-output go together")
    generate(args.configs, args.output)
    if args.game:
        config_path = next(p for p in args.configs if tomllib.loads(p.read_text())["game"]["id"] == args.game)
        generate_game_config(config_path, args.game, args.game_output)


if __name__ == "__main__":
    main()
