# Invoked at build time so runtime edits refresh the handshake identity without
# re-running ROM discovery or regenerating the entire native program.
set(identity "${COMPILER_ID}")
foreach(source IN LISTS SOURCES)
    file(SHA256 "${SOURCE_DIR}/${source}" digest)
    string(APPEND identity ";${source}:${digest}")
endforeach()
foreach(generated_dir IN ITEMS "${GENERATED_DIR}" "${SOUND_GENERATED_DIR}")
    if(generated_dir)
        file(GLOB generated_files RELATIVE "${generated_dir}" "${generated_dir}/*.c" "${generated_dir}/*.h")
        list(SORT generated_files)
        foreach(source IN LISTS generated_files)
            file(SHA256 "${generated_dir}/${source}" digest)
            string(APPEND identity ";generated/${source}:${digest}")
        endforeach()
    endif()
endforeach()
string(SHA256 hash "${identity}")
set(content "#pragma once\n#define F3_NETPLAY_BUILD_HASH \"${hash}\"\n")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" old)
    if(old STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${content}")
